### ISSUE TITLE
refactorer `termine?` dans les restitutions ?

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva-serveur#417]
cf ce commentaire d'Etienne https://github.com/betagouv/eva-serveur/pull/396#discussion_r404872296

Depuis que  nous avons introduit l'événement de fin, il est devenu inutile de compter le nombre de questions pour déterminer la fin des MES de types questions

Malheureusement, pour une question de compatiblité avec de vielles restitutions du bureau, on doit garder le code dans la restitution Question.

On peut malgré tout supprimer ce code pour la restitution Livraison.

Roadmap :

- [x] Supprimer la surcharge de Livraison betagouv/eva-serveur#409
- [x] Migrer les données des anciennes évaluations pour s'assurer que toutes les Parties terminées aient bien un événement fin #434 et #440 
- [ ] S'assurer que le dernier événement est bien un évenement de fin de situation ( ou un abandon ) #438 
- [ ] Supprimer la surcharge de Controle
- [x] Supprimer la surcharge de Inventaire
- [ ] Supprimer la surcharge de Questions
- [ ] Supprimer la surcharge de Securite
- [ ] Supprimer la surcharge de Tri

**Comment by shanser** [comment]
c'est passé dans Trello https://trello.com/c/YmHXXzaI/16-refactorer-termine-dans-les-restitutions-417
